dist: bionic
language: cpp
sudo: false

compiler:
- clang
- gcc

addons:
  postgresql: "9.3"
  apt:
    sources:
    - llvm-toolchain-precise-3.5
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - clang-3.5
    - flex
    - g++-4.9
    - libpq-dev
    - libpq5
    - libstdc++6
    - libtool
    - pkg-config

script: ./travis-build.sh

cache:
  directories:
  - $HOME/.ccache
  - .libs

notifications:
  email: false
  
branches:
 only:
 - auto
